apiVersion: v1
kind: Service
metadata:
  name: keycloak-postgres-svc
  namespace: keycloak
spec:
  selector:
    app: keycloak-postgresql-ss
  type: LoadBalancer
  ports:
  - port: 5432
    targetPort: 5432
 