kind: Secret
apiVersion: v1
metadata:
  name: keycloak-instance-1-initial-admin
  namespace: keycloak
stringData:
  password: <admin-password>
  username: <admin-username>
type: kubernetes.io/basic-auth