kind: Secret
apiVersion: v1
metadata:
  name: keycloak-db-secret
  namespace: keycloak
stringData:
  POSTGRES_DATABASE: "keycloak"
  POSTGRES_EXTERNAL_ADDRESS: "keycloak-postgres-svc.keycloak.svc.cluster.local"
  POSTGRES_EXTERNAL_PORT: "5432"
  POSTGRES_HOST: "keycloak-postgres-svc.keycloak.svc.cluster.local:5432"
  POSTGRES_PASSWORD: "12345678"
  POSTGRES_SUPERUSER: "true"
  POSTGRES_USERNAME: "admin"
type: Opaque