apiVersion: v1
kind: Secret
metadata:
  name: dhi-secrets
  namespace: librechat
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "dhi.io": {
          "username": "docker-username",
          "password": "docker-token",
          "email": "docker-email"
        }
      }
    }
    