apiVersion: v1
kind: Secret
metadata:
  name: librechat-credentials-env
  namespace: librechat
type: Opaque
stringData:
  CREDS_KEY: b951e36bd46b94a795200be17b1e86aa54cbcb79495685fb8265b2fd54fd1775
  JWT_SECRET: 0f8c68a72ce1686454f62b138ac387a8
  JWT_REFRESH_SECRET: b1277790f96e32666ffa91ca4c891cd07ea29431faaf9d8a8330ad788d0db0af
  MONGO_URI: "mongodb://<mongodb-root-username>:<mongodb-root-password>@librechat-mongodb:27017/LibreChat?authSource=admin" # root:rootPass
  OPENID_CLIENT_SECRET: <keycloak-client-secret> # -- Update with Realm librechat-ID Client Secrets
  OPENID_SESSION_SECRET: "a3f9c8e6d4b2e1f0a9c7d5e3b1f4c6a8d0e2f9c7a5b4d3e1c6f8a9b0d2e4"
  MEILI_MASTER_KEY: 640185d16f86e31648a07df708477ae0
  